### ISSUE TITLE
改进提议

### ISSUE THREAD

**Issue by lilijreey** [owenliang/zkclient#1]
你好，最近也在开zk的C++client。 README写的不错很有收货。 
看了一下代码，感觉有几点可以设计的更好或者这说有几点设计的不是很好。
1. 使用单例模式。 
  这个限制的其他人使用你代码的扩展性。 个人觉得应该不要采用单利模式。 而是让用户来选择
是只创建一个函数多个。 显然C的bind是可以创建多个的。
2. 接口抽象度不够。 可以使用模板方法模式。 抽象回调。增加内聚性。
3. 接口功能是不有点少。 没有看到递归get，和递归创建node的接口。

**Comment by owenliang** [comment]
@lilijreey 这份代码主要是用于服务化场景，所以做成了单例。重点还是提供思路和坑点，帮助大家上手实现自己的zk client。
